---
layout: post
title: 콜백 지옥에서 탈출하기
description: >
    콜백 지옥에서 탈출하기 스터디
sitemap: false
hide_last_modified: false
categories:
  - subcat
  - fe
---

## 📌콜백 지옥이란 무엇일까?
~~~
step1(function (value1) {
  step2(function (value2) {
    step3(function (value3) {
      step4(function (value4) {
        step5(function (value5) {
          step6(function (value6) {
            step7(function (value7) {
                console.log(value7);
              })
            })
          })
        })
      })
    })
  })
~~~
위 코드처럼 연속된 비동기함수를 처리할 때 비동기의 처리값을 사용할 때 계속 콜백함수가 깊어지는 것이다.

## 📌콜백 지옥에서 탈출하기


![그림1](/assets/img/blog/study/promise.png)
~~~
Pending은 대기상태로 현재 비동기 작업이 진행 중이거나 시작할 수 없는 문제가 발생했다를 나타낸다.

Fulfilled는 이행 또는 성공 상태로 비동기 작업이 의도한대로 정상적으로 완료된 상태를 나타낸다.

Rejected는 거부 또는 실패했다는 상태로 비동기 작업이 모종의 이유로 실패했음을 나타낸다.
ex) 서버가 응답하지 않는다. 오래걸려서 자동으로 취소

Pending 상태에서 Fulfilled로 되는 과정을 resolve, Pending에서 Rejected가 되면 reject라고 한다.
~~~

#### 한 번 해보기
~~~
function inPositive(number, resolve, reject) {
  setTimeout(()=> {
    if(typeof number === 'number') {
      //성공 -> resolve
      resolve(number >=0 ? "양수" : "음수");
    } esle {
      //실패 -> reject
      reject("주어진 값이 숫자형 값이 아닙니다");
    }
  }, 2000)
}
~~~
기본
~~~
isPositive(10, (res)=>{
  console.log('성공적으로 수행됨 : ', res);
  }, (err)=>{
    console.log('실패하였음 : ', err);
    });
~~~
성공적으로 수행됨 : 양수
~~~

isPositive([], (res)=>{
  console.log('성공적으로 수행됨 : ', res);
  }, (err)=>{
    console.log('실패하였음 : ', err);
    });
~~~
실패하였음 : 주어진 값이 숫자형 값이 아님니다

#### Promise를 활용하기

~~~
function isPositiveP (number) {
  const executor = (resolve, reject) => { // executor = 실행자
    setTimeout(() => {
      setTimeout(()=> {
        if(typeof number === 'number') {
          //성공 -> resolve
          resolve(number >=0 ? "양수" : "음수");
        } esle {
          //실패 -> reject
          reject("주어진 값이 숫자형 값이 아닙니다");
        }
      }, 2000);
  };

  const asyncTask = new Promise(executor);
  return asyncTask;
}

const res = isPositive(101);

res
  .then((res)=> {
    console.log('작업 성공 : ', res);
    })
    .catch((err) => {
      console.log("작업 실패 : ", err);
      });
~~~

#### 동기, 비동기 때 썼던 코드를 Promise로 바꿔보기
~~~
 function taskA(a, b, cb) {
   setTimeout(() => {
     const res = a + b;
     cb(res);
     }, 3000);
 }

 function taskB(a, cb) {
   setTimeout(() => {
     const res = a * 2;
     cb(res);
     }, 1000);
 }

 function taskC(a, cb) {
   setTimeout(() => {
     const res = a * -1;
     cb(res);
     }, 2000);
 }

-----------------------
 taskA(3, 4, (a_res)=> {
   console.log('taskA: ', a_res);
   taskB(a_res, (b_res)=> {
     console.log('taskB: ', b_res);
     taskC(b_res, (c_res)=> {
       console.log('taskC: ', c_res);
       })
     })
   });
//콜백 지옥 식
-----------------------
 ~~~
